database_name: source
table_name:
  - geolocation
  - sellers
  - customers
  - orders
  - order_payments
  - products
  - order_items
  - order_reviews
geolocation:
  - geolocation_zip_code_prefix
  - geolocation_lat
  - geolocation_lng
  - geolocation_city
  - geolocation_state
sellers:
  - seller_id
  - seller_zip_code_prefix
  - seller_city
  - seller_state
customers:
  - customer_id
  - customer_unique_id
  - customer_zip_code_prefix
  - customer_city
  - customer_state
orders:
  - order_id
  - customer_id
  - order_status
  - order_purchase_timestamp
  - order_approved_at
  - order_delivered_carrier_date
  - order_delivered_customer_date
  - order_estimated_delivery_date
order_payments:
  - order_id
  - payment_sequential
  - payment_type
  - payment_installments
  - payment_value
products:
  - product_id
  - product_category_name
  - product_name_length
  - product_description_length
  - product_photos_qty
  - product_weight_g
  - product_length_cm
  - product_height_cm
  - product_width_cm
order_items:
  - order_id
  - order_item_id
  - product_id
  - seller_id
  - shipping_limit_date
  - price
  - freight_value
order_reviews:
  - review_id
  - order_id
  - review_score
  - review_creation_date
# Can only get the information about neighbour table and reference when go to farther table
foreign_keys:
  geolocation:
    sellers:
      local: geolocation_zip_code_prefix
      remote: seller_zip_code_prefix
    customers:
      local: geolocation_zip_code_prefix
      remote: customer_zip_code_prefix
    orders: customers
    order_payments: customers
    products: customers # or sellers
    order_items: customers
    order_reviews: customers
  sellers:
    geolocation:
      local: seller_zip_code_prefix
      remote: geolocation_zip_code_prefix
    customers: order_items
    orders: order_items
    order_payments: order_items
    products: order_items
    order_items:
      local: seller_id
      remote: seller_id
    order_reviews: order_items
  customers:
    geolocation:
      local: customer_zip_code_prefix
      remote: geolocation_zip_code_prefix
    sellers: orders
    orders:
      local: customer_id
      remote: customer_id
    order_payments: orders
    products: orders
    order_items: orders
    order_reviews: orders
  orders:
    geolocation: customers # or sellers
    sellers: order_items
    customers:
      local: customer_id
      remote: customer_id
    order_payments:
      local: order_id
      remote: order_id
    products: order_items
    order_items:
      local: order_id
      remote: order_id
    order_reviews:
      local: order_id
      remote: order_id
  order_payments:
    geolocation: orders
    sellers: orders
    customers: orders
    orders:
      local: order_id
      remote: order_id
    products: orders
    order_items: orders
    order_reviews: orders
  products:
    geolocation: order_items
    sellers: order_items
    customers: order_items
    orders: order_items
    order_payments: order_items
    order_items:
      local: product_id
      remote: product_id
    order_reviews: order_items
  order_items:
    geolocation: orders # [customer] or seller
    sellers:
      local: seller_id
      remote: seller_id
    customers: orders
    orders:
      local: order_id
      remote: order_id
    order_payments: orders
    products:
      local: product_id
      remote: product_id
    order_reviews: orders
  order_reviews:
    geolocation: orders
    sellers: orders
    customers: orders
    orders:
      local: order_id
      remote: order_id
    order_payments: orders
    products: orders
    order_items: orders
primary_keys:
  geolocation:
    - geolocation_zip_code_prefix
  sellers:
    - seller_id
  customers:
    - customer_id
  orders:
    - order_id
  order_payments:
    - order_id
    - payment_sequential
  products:
    - product_id
  order_items:
    - order_id
    - order_item_id
  order_reviews:
    - order_id
    - review_id

# geolocation
# geolocation_zip_code_prefix CHAR(5),
# geolocation_lat FLOAT,
# geolocation_lng FLOAT,
# geolocation_city VARCHAR(64),
# geolocation_state CHAR(2),
# 
# sellers 
# seller_id CHAR(32),
# seller_zip_code_prefix CHAR(5),
# seller_city VARCHAR(64),
# seller_state CHAR(2),
# FOREIGN KEY (seller_zip_code_prefix) REFERENCES geolocation(geolocation_zip_code_prefix)
# 
# customers 
# customer_id CHAR(32),
# customer_unique_id CHAR(32),
# customer_zip_code_prefix CHAR(5),
# customer_city VARCHAR(64),
# customer_state CHAR(2),1
# FOREIGN KEY (customer_zip_code_prefix) REFERENCES geolocation(geolocation_zip_code_prefix)
# 
# orders 
# order_id CHAR(32),
# customer_id CHAR(32),
# order_status VARCHAR(20),
# order_purchase_timestamp TIMESTAMP,
# order_approved_at TIMESTAMP,
# order_delivered_carrier_date TIMESTAMP,
# order_delivered_customer_date TIMESTAMP,
# order_estimated_delivery_date DATE,
# 
# order_payments 
# order_id CHAR(32),
# payment_sequential INTEGER,
# payment_type VARCHAR(20),
# payment_installments INTEGER,
# payment_value FLOAT,
# FOREIGN KEY (order_id) REFERENCES orders(order_id)
# 
# products 
# product_id CHAR(32) PRIMARY KEY,
# product_category_name VARCHAR(64),
# product_name_length INTEGER,
# product_description_length INTEGER,
# product_photos_qty INTEGER,
# product_weight_g INTEGER,
# product_length_cm INTEGER,
# product_height_cm INTEGER,
# product_width_cm INTEGER,
# 
# order_items 
# order_id CHAR(32),
# order_item_id INTEGER,
# product_id CHAR(32),
# seller_id CHAR(32),
# shipping_limit_date TIMESTAMP,
# price FLOAT,
# freight_value FLOAT,
# FOREIGN KEY (order_id) REFERENCES orders(order_id)
# FOREIGN KEY (product_id) REFERENCES products(product_id)
# 
# order_reviews 
# review_id CHAR(32),
# order_id CHAR(32),
# review_score INTEGER,
# review_creation_date DATE,
# FOREIGN KEY (order_id) REFERENCES orders(order_id)
