[connections.source]
    type="sql"
    dialect="mariadb"
    username="user_431"
    password="user_431"
    host="127.0.0.1" # IP or URL or 'localhost'
    port=3306 # Port number
    database="source" # Database name
