[connections.source]
    type="sql"
    dialect="mariadb"
    username="user_431"
    password="user_431"
    host="127.0.0.1" # IP or URL or 'localhost'
    port=3306 # Port number
    database="source" # Database name

# mariadb -u root -p:
    # CREATE USER 'user_431'@'%' IDENTIFIED BY 'user_431';
    # GRANT ALL PRIVILEGES ON source.* TO 'user_431'@'%';
    # FLUSH PRIVILEGES;
# mariadb -u user_431 -p

